/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.risk.server;

import edu.duke.ece651.risk.shared.RISKMap;
import edu.duke.ece651.risk.shared.Territory;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.TreeMap;

public class App {


    public static void main(String[] args) throws IOException {

        TreeMap<String, Territory> continent = new TreeMap<String, Territory>();
        continent.put("Test1", new Territory("Test1"));
        continent.put("Test2", new Territory("Test2"));
        continent.put("Test3", new Territory("Test3"));
        continent.put("Test4", new Territory("Test4"));
        RISKMap riskMap = new RISKMap(continent);

        ServerSocket servSocket;
        Socket fromClientSocket;
        int cTosPortNumber = 1777;

        servSocket = new ServerSocket(cTosPortNumber);
        System.out.println("Waiting for a connection on " + cTosPortNumber);

        fromClientSocket = servSocket.accept();
        System.out.println("Connection from " + fromClientSocket + "!");
        ObjectOutputStream oos = new ObjectOutputStream(fromClientSocket.getOutputStream());
        ObjectInputStream ois = new ObjectInputStream(fromClientSocket.getInputStream());


        System.out.println("Sending map to the ServerSocket");
        oos.writeObject(riskMap);


        System.out.println("Closing socket and terminating program.");
        ois.close();
        oos.close();
        fromClientSocket.close();

    }

}
