/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.risk.server;

import java.io.IOException;
import java.net.ServerSocket;
import java.util.Queue;

public class App {

    private static Queue<Client> clientQueue;
    
    public static void main(String[] args) throws IOException {

        RiskGameServer riskGameServer = new RiskGameServer(3,new ServerSocket(1777));
        riskGameServer.start();
    }

}
