version: "3.3"
services:
  apiserver:
    build:
      context: .
      dockerfile: Dockerfile_apiServer
    depends_on:
            - mysql
            - mongodb
    ports:
      - "8080:8080"
    expose:
      - '8080'
  mysql:
     image: "mysql:5"
     environment:
             MYSQL_ROOT_PASSWORD: 'bDdb7TjCstDNWykX'
             MYSQL_DATABASE: 'testdb'
     ports:
             - '3306:3306'
     expose:
             - '3306'
  mongodb:
          image: "mongo:4.4.6"
          environment:
                  MONGO_INITDB_ROOT_USERNAME: "mongoadmin"
                  MONGO_INITDB_ROOT_PASSWORD: "bDdb7TjCstDNWykX"

          ports:
                  - '27017:27017'
          expose:
                  - '27017'
  webserver:
          build: 
                context: .
                dockerfile: Dockerfile_webServer
          ports:
                  - "8081:8081"
          expose:
                  - '8081'
          depends_on:
                - apiserver

          
