# syntax=docker/dockerfile:1
FROM gradle:7.4.1-jdk17
WORKDIR /ece651-RISK
COPY . .
RUN gradle resolveDependencies
RUN gradle --build-cache assemble
EXPOSE 8080
CMD ["java", "-jar", "./apiserver/build/libs/apiserver-0.0.1-SNAPSHOT.jar"] 
