/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.risk.shared;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertEquals(classUnderTest.someLibraryMethod(), "Hello World from shared");
    }
}
