/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.risk.client;

import edu.duke.ece651.risk.shared.*;

import java.io.*;

public class App {

    public static void main(String[] args) throws IOException, ClassNotFoundException {

        ClientContext context = new ClientContext();
        context.setBufferedReader(new BufferedReader(new InputStreamReader(System.in)));
        context.setOut(System.out);
        RiskGameClient client = new RiskGameClient(context,1777);
        client.start();


    }
}
